/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlarmHeatmapChart: typeof import('./components/charts/AlarmHeatmapChart.vue')['default']
    AlarmImageViewer: typeof import('./components/business/AlarmImageViewer.vue')['default']
    AppBreadcrumb: typeof import('./components/layout/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    ConfirmDialog: typeof import('./components/common/ConfirmDialog.vue')['default']
    DataTable: typeof import('./components/common/DataTable.vue')['default']
    DeviceHealthChart: typeof import('./components/charts/DeviceHealthChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    InferenceTrendChart: typeof import('./components/charts/InferenceTrendChart.vue')['default']
    ModelAccuracyChart: typeof import('./components/charts/ModelAccuracyChart.vue')['default']
    ModelStatusStepper: typeof import('./components/business/ModelStatusStepper.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PermissionButton: typeof import('./components/common/PermissionButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SandboxCompareViewer: typeof import('./components/business/SandboxCompareViewer.vue')['default']
    SearchBar: typeof import('./components/common/SearchBar.vue')['default']
    StatusBadge: typeof import('./components/common/StatusBadge.vue')['default']
    WorkflowNode: typeof import('./components/business/WorkflowNode.vue')['default']
  }
}
